name: flutter_stetho_example
description: Demonstrates how to use the stetho_network_inspector plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  stetho_network_inspector:
    path: ../

flutter:
  uses-material-design: true
